(function(){
  'use strict';
  var API='http://127.0.0.1:8765',token=sessionStorage.getItem('hama_admin_token')||'',documents=[],pollTimer=null;
  var $=function(s){return document.querySelector(s)},dialog=$('#loginDialog'),rows=$('#docRows'),toast=$('#toast');
  function headers(extra){return Object.assign({'X-Admin-Token':token},extra||{})}
  async function api(path,options){var response=await fetch(API+path,Object.assign({},options||{},{headers:headers(options&&options.headers)}));var data=await response.json().catch(function(){return{detail:'Server response is invalid'}});if(!response.ok)throw new Error(data.detail||'Request failed');return data}
  function notify(message,error){toast.textContent=message;toast.style.borderLeftColor=error?'#e24b3f':'#d8a719';toast.classList.add('show');setTimeout(function(){toast.classList.remove('show')},3200)}
  function formatSize(bytes){if(bytes<1024*1024)return(bytes/1024).toFixed(0)+' KB';return(bytes/1024/1024).toFixed(1)+' MB'}
  function escapeHtml(value){var d=document.createElement('div');d.textContent=value;return d.innerHTML}
  function statusFor(doc){if(doc.expired)return['Expired','expired'];if(!doc.active)return['Disabled','disabled'];return['Active','']}
  function render(){var query=$('#searchInput').value.toLowerCase(),filtered=documents.filter(function(d){return d.filename.toLowerCase().indexOf(query)>-1});rows.innerHTML=filtered.map(function(doc){var st=statusFor(doc),name=escapeHtml(doc.filename);return '<tr data-name="'+name+'"><td><div class="doc-name"><span class="pdf-icon">PDF</span><span><strong title="'+name+'">'+name+'</strong><small>'+(doc.indexed_chunks?'Inatumika kwenye chatbot':'Inasubiri rebuild')+'</small></span></div></td><td>'+formatSize(doc.size)+'</td><td>'+doc.indexed_chunks+'</td><td><input class="expiry" type="date" value="'+(doc.expires_on||'')+'" aria-label="Expiry '+name+'"></td><td><span class="status '+st[1]+'">'+st[0]+'</span></td><td><div class="actions"><button class="toggle '+(doc.active?'on':'')+'" data-toggle title="Washa au zima"><i></i></button><button class="row-btn danger" data-delete title="Futa waraka"><svg viewBox="0 0 24 24"><path d="M4 7h16M9 7V4h6v3M7 7l1 13h8l1-13M10 11v5M14 11v5"/></svg></button></div></td></tr>'}).join('');$('#emptyState').hidden=filtered.length>0;bindRows();updateCounts()}
  function updateCounts(){var active=documents.filter(function(d){return d.active&&!d.expired}).length,expired=documents.filter(function(d){return d.expired}).length,chunks=documents.reduce(function(n,d){return n+d.indexed_chunks},0);$('#docTotal').textContent=documents.length;$('#activeTotal').textContent=active;$('#expiredTotal').textContent=expired;$('#chunkTotal').textContent=chunks}
  async function saveDoc(doc){await api('/api/admin/documents/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({filename:doc.filename,active:doc.active,expires_on:doc.expires_on||''})});notify('Mabadiliko yamehifadhiwa. Jenga index mpya.');await load()}
  function bindRows(){rows.querySelectorAll('tr').forEach(function(row){var doc=documents.find(function(d){return d.filename===row.dataset.name});row.querySelector('[data-toggle]').onclick=function(){doc.active=!doc.active;saveDoc(doc).catch(fail)};row.querySelector('.expiry').onchange=function(e){doc.expires_on=e.target.value;saveDoc(doc).catch(fail)};row.querySelector('[data-delete]').onclick=async function(){if(!confirm('Futa kabisa "'+doc.filename+'"? Hatua hii haiwezi kurudishwa.'))return;try{await api('/api/admin/documents/delete',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({filename:doc.filename})});notify('Waraka umefutwa. Jenga index mpya.');await load()}catch(e){fail(e)}}})}
  function fail(error){notify(error.message||String(error),true)}
  async function load(){var data=await api('/api/admin/documents');documents=data.documents;render();updateRebuild(data.rebuild);$('#systemStatus').textContent='Tayari'}
  function updateRebuild(state){$('#indexMessage').textContent=state.message||state.stage;$('#rebuildBtn').disabled=!!state.running;$('#rebuildBtn').textContent=state.running?'Inaendelea...':'Jenga index mpya';if(state.running&&!pollTimer)pollTimer=setInterval(checkRebuild,2500);if(!state.running&&pollTimer){clearInterval(pollTimer);pollTimer=null}}
  async function checkRebuild(){try{var state=await api('/api/admin/rebuild');updateRebuild(state);if(!state.running){await load();notify(state.stage==='ready'?'Index mpya iko tayari.':'Rebuild imeshindwa: '+state.message,state.stage!=='ready')}}catch(e){fail(e)}}
  $('#loginForm').addEventListener('submit',async function(e){e.preventDefault();token=$('#tokenInput').value.trim();try{await load();sessionStorage.setItem('hama_admin_token',token);dialog.close()}catch(err){$('#loginError').textContent=err.message}});
  $('#fileInput').onchange=function(e){var file=e.target.files[0];$('#fileLabel').textContent=file?file.name:'Chagua PDF';$('#uploadBtn').disabled=!file};
  $('#uploadBtn').onclick=async function(){var file=$('#fileInput').files[0];if(!file)return;this.disabled=true;this.textContent='Inapakia...';try{var expiry=$('#uploadExpiry').value,url='/api/admin/documents/upload'+(expiry?'?expires_on='+encodeURIComponent(expiry):'');await api(url,{method:'POST',headers:{'Content-Type':'application/pdf','X-Filename':encodeURIComponent(file.name)},body:file});notify('Waraka umepakiwa. Jenga index mpya.');$('#fileInput').value='';$('#fileLabel').textContent='Chagua PDF';$('#uploadExpiry').value='';await load()}catch(e){fail(e)}finally{this.textContent='Pakia';this.disabled=!$('#fileInput').files[0]}};
  $('#rebuildBtn').onclick=async function(){try{await api('/api/admin/rebuild',{method:'POST'});notify('Rebuild imeanza. Chatbot inaendelea kutumia index ya zamani.');await checkRebuild()}catch(e){fail(e)}};
  $('#searchInput').oninput=render;
  if(token){load().catch(function(){token='';sessionStorage.removeItem('hama_admin_token');dialog.showModal()})}else dialog.showModal();
})();
